name: to_do_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.5

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bloc: ^8.1.3
  date_picker_timeline: ^1.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.4
  get_it: ^7.6.7
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/icon/app_icon.png
    - assets/images/no_tasks.png
    -	assets/images/on1.png
    -	assets/images/on2.png
    -	assets/images/on3.png
