name: to_do_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  date_picker_timeline: ^1.2.5
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/icon/app_icon.png
    - assets/images/no_tasks.png
    -	assets/images/on1.png
    -	assets/images/on2.png
    -	assets/images/on3.png
